[toolchain]
channel = "stable"
components = [ "rustc", "cargo", "clippy", "rustfmt", "rust-analyzer" ]
targets = [
  "wasm32-unknown-unknown",
  "x86_64-unknown-linux-gnu",
  "aarch64-linux-android",
  "armv7-linux-androideabi",
  "x86_64-linux-android",
  "i686-linux-android"
]

profile = "default"
